---
- name: Play-1.... 
  hosts: linux 
  become: true
  tasks: 
    - name: Install git on ubuntu
      apt:
        name: git
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"   
    
    - name: Install git on centos
      yum:
        name: git
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"
